# Site settings
title: Mero Code
email: timsinanabin@gmail.com
description: "Adventures in Computer Science"
baseurl: ""
url: "merocode.github.io"
highlighter: pygments
gravatar: https://avatars1.githubusercontent.com/u/405628?s=50

# Build settings
markdown: kramdown
permalink: pretty
